name: hackathon_project_x
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  shared_preferences: ^2.2.2
  http: ^1.3.0
  provider: ^6.1.0  # Оставь последнюю версию здесь
  video_player: ^2.7.2  # Перемести из dev_dependencies сюда

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  table_calendar: ^3.0.9


flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/profile.png
    - assets/video/video1.mp4
    - assets/video/video11.mp4


